plugins {
    id 'java'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes(
                'Main-Class': 'Main'
        )
    }
}

task createJar(type: Jar) {
    archiveBaseName.set('horse-race')
    archiveVersion.set(version)
    from sourceSets.main.output
    manifest {
        attributes 'Main-Class': 'java.Main'
    }
}